#ifndef PRAGMA_AMIHTTP_LIB_H
#define PRAGMA_AMIHTTP_LIB_H

/*
** Aztec 'C', Maxon 'C' and StormC format pragma files
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_AMIHTTP_PROTOS_H
#include <clib/amihttp_protos.h>
#endif /* CLIB_AMIHTTP_PROTOS_H */

/*"amihttp.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process configuration (after OpenLibrary only). */

/* Bootstrap: OpenLibrary(AMIHTTPNAME, AMIHTTPVERSION) is sufficient.  bsdsocket */
/* opens on first HTTP use; amisslmaster / OpenAmiSSLTags on first HTTPS use */

#pragma amicall(HttpBase, 0x1E, HttpBaseTagList(a0))
#pragma amicall(HttpBase, 0x24, HttpError())
#pragma amicall(HttpBase, 0x2A, HttpGetErrorString(d0))

/* Tier 1 - HttpSession persistent client context. */

#pragma amicall(HttpBase, 0x30, NewHttpSession())
#pragma amicall(HttpBase, 0x36, DisposeHttpSession(a0))
#pragma amicall(HttpBase, 0x3C, SetHttpSessionAttrsA(a0,a1))
#pragma amicall(HttpBase, 0x42, HttpSessionAttachCookieJar(a0,a1))
#pragma amicall(HttpBase, 0x48, HttpSessionDetachCookieJar(a0))
#pragma amicall(HttpBase, 0x4E, SetHttpSessionHook(a0,d0,a1))

/* Tier 2 - HttpTransaction request/response (primary API). */

#pragma amicall(HttpBase, 0x54, NewHttpTransaction(a0))
#pragma amicall(HttpBase, 0x5A, DisposeHttpTransaction(a0))
#pragma amicall(HttpBase, 0x60, SetHttpTransactionAttrsA(a0,a1))
#pragma amicall(HttpBase, 0x66, HttpTransactionAddHeader(a0,a1,a2))
#pragma amicall(HttpBase, 0x6C, HttpTransactionClearHeaders(a0))
#pragma amicall(HttpBase, 0x72, HttpTransactionPerform(a0))
#pragma amicall(HttpBase, 0x78, HttpTransactionPerformAsync(a0))
#pragma amicall(HttpBase, 0x7E, HttpTransactionIsComplete(a0))
#pragma amicall(HttpBase, 0x84, WaitHttpTransaction(a0,d0))
#pragma amicall(HttpBase, 0x8A, AbortHttpTransaction(a0))
#pragma amicall(HttpBase, 0x90, HttpTransactionGetStatusCode(a0))
#pragma amicall(HttpBase, 0x96, HttpTransactionGetStatusLine(a0))
#pragma amicall(HttpBase, 0x9C, HttpTransactionRespHeader(a0,a1))
#pragma amicall(HttpBase, 0xA2, HttpTransactionRespHeaders(a0))
#pragma amicall(HttpBase, 0xA8, HttpTransactionReadBody(a0,a1,d0))
#pragma amicall(HttpBase, 0xAE, HttpTransactionGetRedirectLocation(a0))
#pragma amicall(HttpBase, 0xB4, HttpTransactionGetContentLength(a0))
#pragma amicall(HttpBase, 0xBA, HttpTransactionGetBytesReceived(a0))
#pragma amicall(HttpBase, 0xC0, HttpTransactionGetTiming(a0,a1))
#pragma amicall(HttpBase, 0xC6, HttpTransactionGetLastError(a0))
#pragma amicall(HttpBase, 0xCC, SetHttpTransactionHook(a0,d0,a1))

/* Tier 3 - HttpConnection streaming / WebDAV / custom protocols. */

#pragma amicall(HttpBase, 0xD2, OpenHttpConnection(a0,a1,d0,d1))
#pragma amicall(HttpBase, 0xD8, CloseHttpConnection(a0))
#pragma amicall(HttpBase, 0xDE, HttpConnectionWrite(a0,a1,d0))
#pragma amicall(HttpBase, 0xE4, HttpConnectionRead(a0,a1,d0))
#pragma amicall(HttpBase, 0xEA, HttpConnectionSendRequest(a0,a1,a2,a3))
#pragma amicall(HttpBase, 0xF0, HttpConnectionReadResponseLine(a0,a1,d0))
#pragma amicall(HttpBase, 0xF6, HttpConnectionReadResponseHeaders(a0))
#pragma amicall(HttpBase, 0xFC, HttpConnectionReadBodyChunk(a0,a1,d0))
#pragma amicall(HttpBase, 0x102, HttpConnectionWriteBodyChunk(a0,a1,d0))
#pragma amicall(HttpBase, 0x108, HttpConnectionIsAlive(a0))
#pragma amicall(HttpBase, 0x10E, ResetHttpConnection(a0))
#pragma amicall(HttpBase, 0x114, HttpConnectionRespHeader(a0,a1))
#pragma amicall(HttpBase, 0x11A, HttpConnectionRespHeaders(a0))
#pragma amicall(HttpBase, 0x120, HttpConnectionGetStatusCode(a0))
#pragma amicall(HttpBase, 0x126, HttpConnectionGetStatusLine(a0))

/* URL parsing and encoding utilities. */

#pragma amicall(HttpBase, 0x12C, ParseHttpUrl(a0))
#pragma amicall(HttpBase, 0x132, DisposeHttpUrl(a0))
#pragma amicall(HttpBase, 0x138, BuildHttpUrl(a0))
#pragma amicall(HttpBase, 0x13E, HttpUrlEncode(a0))
#pragma amicall(HttpBase, 0x144, HttpUrlDecode(a0))
#pragma amicall(HttpBase, 0x14A, HttpPathEncode(a0))
#pragma amicall(HttpBase, 0x150, HttpBuildQueryString(a0))

/* Optional HttpCookieJar (attach via HttpSessionAttachCookieJar). */

#pragma amicall(HttpBase, 0x156, NewHttpCookieJar())
#pragma amicall(HttpBase, 0x15C, DisposeHttpCookieJar(a0))
#pragma amicall(HttpBase, 0x162, LoadHttpCookieJar(a0,a1))
#pragma amicall(HttpBase, 0x168, SaveHttpCookieJar(a0,a1))
#pragma amicall(HttpBase, 0x16E, FlushHttpCookieJar(a0,d0))
#pragma amicall(HttpBase, 0x174, SetHttpCookie(a0,a1))
#pragma amicall(HttpBase, 0x17A, GetHttpCookieString(a0,a1))
#pragma amicall(HttpBase, 0x180, SetHttpError(d0))
#pragma amicall(HttpBase, 0x186, HttpFault(d0,a0,a1,d1))

/* URL part helpers (dos PathPart/FilePart style; caller frees with Free()). */

#pragma amicall(HttpBase, 0x18C, HttpUriSchemePart(a0))
#pragma amicall(HttpBase, 0x192, HttpUriHostPart(a0))
#pragma amicall(HttpBase, 0x198, HttpUriPathPart(a0))
#pragma amicall(HttpBase, 0x19E, HttpUriFilePart(a0))
#pragma amicall(HttpBase, 0x1A4, HttpUriQueryPart(a0))
#pragma amicall(HttpBase, 0x1AA, HttpUriParentPart(a0))
#pragma amicall(HttpBase, 0x1B0, HttpUriAuthorityPart(a0))
#pragma amicall(HttpBase, 0x1B6, HttpJoinUri(a0,a1))

/* TLS peer certificate (after HTTPS HttpTransactionPerform). */

#pragma amicall(HttpBase, 0x1BC, HttpTransactionGetPeerCert(a0,a1))
#pragma amicall(HttpBase, 0x1C2, HttpPeerCertFree(a0))
#pragma amicall(HttpBase, 0x1C8, HttpTransactionRespHeaderNext(a0,a1,a2))
#pragma amicall(HttpBase, 0x1CE, HttpTransactionRespHeaderByIndex(a0,d0,a1,a2))
#pragma amicall(HttpBase, 0x1D4, NewHttpCookieJarTags(a0))
#pragma amicall(HttpBase, 0x1DA, HttpTransactionGetCipher(a0,a1,d0))

#endif /* PRAGMA_AMIHTTP_LIB_H */
