#ifndef PRAGMAS_AMIHTTP_PRAGMAS_H
#define PRAGMAS_AMIHTTP_PRAGMAS_H

/*
** Lattice 'C', Aztec 'C', SAS/C and DICE format pragma files.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifndef CLIB_AMIHTTP_PROTOS_H
#include <clib/amihttp_protos.h>
#endif /* CLIB_AMIHTTP_PROTOS_H */

/*"amihttp.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process configuration (after OpenLibrary only). */

/* Bootstrap: OpenLibrary(AMIHTTPNAME, AMIHTTPVERSION) is sufficient.  bsdsocket */
/* opens on first HTTP use; amisslmaster / OpenAmiSSLTags on first HTTPS use */

#pragma libcall HttpBase HttpBaseTagsA 1E 801
#if defined(__SASC_60)
#pragma tagcall HttpBase HttpBaseTags 1E 801
#endif /* __SASC_60 */
#pragma libcall HttpBase HttpError 24 00
#pragma libcall HttpBase HttpGetErrorString 2A 001

/* Tier 1 - HttpSession persistent client context. */

#pragma libcall HttpBase NewHttpSession 30 00
#pragma libcall HttpBase DisposeHttpSession 36 801
#pragma libcall HttpBase SetHttpSessionAttrsA 3C 9802
#if defined(__SASC_60)
#pragma tagcall HttpBase SetHttpSessionAttrs 3C 9802
#endif /* __SASC_60 */
#pragma libcall HttpBase HttpSessionAttachCookieJar 42 9802
#pragma libcall HttpBase HttpSessionDetachCookieJar 48 801
#pragma libcall HttpBase SetHttpSessionHook 4E 90803

/* Tier 2 - HttpTransaction request/response (primary API). */

#pragma libcall HttpBase NewHttpTransaction 54 801
#pragma libcall HttpBase DisposeHttpTransaction 5A 801
#pragma libcall HttpBase SetHttpTransactionAttrsA 60 9802
#if defined(__SASC_60)
#pragma tagcall HttpBase SetHttpTransactionAttrs 60 9802
#endif /* __SASC_60 */
#pragma libcall HttpBase HttpTransactionAddHeader 66 A9803
#pragma libcall HttpBase HttpTransactionClearHeaders 6C 801
#pragma libcall HttpBase HttpTransactionPerform 72 801
#pragma libcall HttpBase HttpTransactionPerformAsync 78 801
#pragma libcall HttpBase HttpTransactionIsComplete 7E 801
#pragma libcall HttpBase WaitHttpTransaction 84 0802
#pragma libcall HttpBase AbortHttpTransaction 8A 801
#pragma libcall HttpBase HttpTransactionGetStatusCode 90 801
#pragma libcall HttpBase HttpTransactionGetStatusLine 96 801
#pragma libcall HttpBase HttpTransactionRespHeader 9C 9802
#pragma libcall HttpBase HttpTransactionRespHeaders A2 801
#pragma libcall HttpBase HttpTransactionReadBody A8 09803
#pragma libcall HttpBase HttpTransactionGetRedirectLocation AE 801
#pragma libcall HttpBase HttpTransactionGetContentLength B4 801
#pragma libcall HttpBase HttpTransactionGetBytesReceived BA 801
#pragma libcall HttpBase HttpTransactionGetTiming C0 9802
#pragma libcall HttpBase HttpTransactionGetLastError C6 801
#pragma libcall HttpBase SetHttpTransactionHook CC 90803

/* Tier 3 - HttpConnection streaming / WebDAV / custom protocols. */

#pragma libcall HttpBase OpenHttpConnection D2 109804
#pragma libcall HttpBase CloseHttpConnection D8 801
#pragma libcall HttpBase HttpConnectionWrite DE 09803
#pragma libcall HttpBase HttpConnectionRead E4 09803
#pragma libcall HttpBase HttpConnectionSendRequest EA BA9804
#pragma libcall HttpBase HttpConnectionReadResponseLine F0 09803
#pragma libcall HttpBase HttpConnectionReadResponseHeaders F6 801
#pragma libcall HttpBase HttpConnectionReadBodyChunk FC 09803
#pragma libcall HttpBase HttpConnectionWriteBodyChunk 102 09803
#pragma libcall HttpBase HttpConnectionIsAlive 108 801
#pragma libcall HttpBase ResetHttpConnection 10E 801
#pragma libcall HttpBase HttpConnectionRespHeader 114 9802
#pragma libcall HttpBase HttpConnectionRespHeaders 11A 801
#pragma libcall HttpBase HttpConnectionGetStatusCode 120 801
#pragma libcall HttpBase HttpConnectionGetStatusLine 126 801

/* URL parsing and encoding utilities. */

#pragma libcall HttpBase ParseHttpUrl 12C 801
#pragma libcall HttpBase DisposeHttpUrl 132 801
#pragma libcall HttpBase BuildHttpUrl 138 801
#pragma libcall HttpBase HttpUrlEncode 13E 801
#pragma libcall HttpBase HttpUrlDecode 144 801
#pragma libcall HttpBase HttpPathEncode 14A 801
#pragma libcall HttpBase HttpBuildQueryString 150 801

/* Optional HttpCookieJar (attach via HttpSessionAttachCookieJar). */

#pragma libcall HttpBase NewHttpCookieJarA 156 801
#if defined(__SASC_60)
#pragma tagcall HttpBase NewHttpCookieJar 156 801
#endif /* __SASC_60 */
#pragma libcall HttpBase DisposeHttpCookieJar 15C 801
#pragma libcall HttpBase LoadHttpCookieJar 162 9802
#pragma libcall HttpBase SaveHttpCookieJar 168 9802
#pragma libcall HttpBase FlushHttpCookieJar 16E 0802
#pragma libcall HttpBase SetHttpCookie 174 9802
#pragma libcall HttpBase GetHttpCookieString 17A 9802
#pragma libcall HttpBase SetHttpError 180 001
#pragma libcall HttpBase HttpFault 186 198004

/* URL part helpers (dos PathPart/FilePart style; caller frees with Free()). */

#pragma libcall HttpBase HttpUriSchemePart 18C 801
#pragma libcall HttpBase HttpUriHostPart 192 801
#pragma libcall HttpBase HttpUriPathPart 198 801
#pragma libcall HttpBase HttpUriFilePart 19E 801
#pragma libcall HttpBase HttpUriQueryPart 1A4 801
#pragma libcall HttpBase HttpUriParentPart 1AA 801
#pragma libcall HttpBase HttpUriAuthorityPart 1B0 801
#pragma libcall HttpBase HttpJoinUri 1B6 9802

/* TLS peer certificate (after HTTPS HttpTransactionPerform). */

#pragma libcall HttpBase HttpTransactionGetPeerCert 1BC 9802
#pragma libcall HttpBase HttpPeerCertFree 1C2 801
#pragma libcall HttpBase HttpTransactionRespHeaderNext 1C8 A9803
#pragma libcall HttpBase HttpTransactionRespHeaderByIndex 1CE A90804
#pragma libcall HttpBase HttpTransactionGetCipher 1D4 09803

#endif /* PRAGMAS_AMIHTTP_PRAGMAS_H */
