#ifndef INLINE_AMIHTTP_PROTOS_H
#define INLINE_AMIHTTP_PROTOS_H

/*
** VBCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"amihttp.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process configuration (after OpenLibrary only). */

/* Bootstrap: OpenLibrary(AMIHTTPNAME, AMIHTTPVERSION) is sufficient.  bsdsocket */
/* opens on first HTTP use; amisslmaster / OpenAmiSSLTags on first HTTPS use */

LONG __HttpBaseTagsA(__reg("a6") void *, __reg("a0") struct TagItem *tags)="\tjsr\t-30(a6)";
#define HttpBaseTagsA(tags) __HttpBaseTagsA(HttpBase, (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
LONG __HttpBaseTags(__reg("a6") void *, ...)="\tmove.l\ta0,-(a7)\n\tlea\t4(a7),a0\n\tjsr\t-30(a6)\n\tmovea.l\t(a7)+,a0";
#define HttpBaseTags(...) __HttpBaseTags(HttpBase, __VA_ARGS__)
#endif

LONG __HttpError(__reg("a6") void *)="\tjsr\t-36(a6)";
#define HttpError() __HttpError(HttpBase)

STRPTR __HttpGetErrorString(__reg("a6") void *, __reg("d0") LONG code)="\tjsr\t-42(a6)";
#define HttpGetErrorString(code) __HttpGetErrorString(HttpBase, (code))


/* Tier 1 - HttpSession persistent client context. */

struct HttpSession *__NewHttpSession(__reg("a6") void *)="\tjsr\t-48(a6)";
#define NewHttpSession() __NewHttpSession(HttpBase)

void __DisposeHttpSession(__reg("a6") void *, __reg("a0") struct HttpSession *session)="\tjsr\t-54(a6)";
#define DisposeHttpSession(session) __DisposeHttpSession(HttpBase, (session))

LONG __SetHttpSessionAttrsA(__reg("a6") void *, __reg("a0") struct HttpSession *session, __reg("a1") struct TagItem *tags)="\tjsr\t-60(a6)";
#define SetHttpSessionAttrsA(session, tags) __SetHttpSessionAttrsA(HttpBase, (session), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
LONG __SetHttpSessionAttrs(__reg("a6") void *, __reg("a0") struct HttpSession *session, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-60(a6)\n\tmovea.l\t(a7)+,a1";
#define SetHttpSessionAttrs(...) __SetHttpSessionAttrs(HttpBase, __VA_ARGS__)
#endif

LONG __HttpSessionAttachCookieJar(__reg("a6") void *, __reg("a0") struct HttpSession *session, __reg("a1") struct HttpCookieJar *jar)="\tjsr\t-66(a6)";
#define HttpSessionAttachCookieJar(session, jar) __HttpSessionAttachCookieJar(HttpBase, (session), (jar))

void __HttpSessionDetachCookieJar(__reg("a6") void *, __reg("a0") struct HttpSession *session)="\tjsr\t-72(a6)";
#define HttpSessionDetachCookieJar(session) __HttpSessionDetachCookieJar(HttpBase, (session))

LONG __SetHttpSessionHook(__reg("a6") void *, __reg("a0") struct HttpSession *session, __reg("d0") ULONG type, __reg("a1") struct Hook *hook)="\tjsr\t-78(a6)";
#define SetHttpSessionHook(session, type, hook) __SetHttpSessionHook(HttpBase, (session), (type), (hook))


/* Tier 2 - HttpTransaction request/response (primary API). */

struct HttpTransaction *__NewHttpTransaction(__reg("a6") void *, __reg("a0") struct HttpSession *session)="\tjsr\t-84(a6)";
#define NewHttpTransaction(session) __NewHttpTransaction(HttpBase, (session))

void __DisposeHttpTransaction(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-90(a6)";
#define DisposeHttpTransaction(txn) __DisposeHttpTransaction(HttpBase, (txn))

LONG __SetHttpTransactionAttrsA(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("a1") struct TagItem *tags)="\tjsr\t-96(a6)";
#define SetHttpTransactionAttrsA(txn, tags) __SetHttpTransactionAttrsA(HttpBase, (txn), (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
LONG __SetHttpTransactionAttrs(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, ...)="\tmove.l\ta1,-(a7)\n\tlea\t4(a7),a1\n\tjsr\t-96(a6)\n\tmovea.l\t(a7)+,a1";
#define SetHttpTransactionAttrs(...) __SetHttpTransactionAttrs(HttpBase, __VA_ARGS__)
#endif

LONG __HttpTransactionAddHeader(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("a1") STRPTR name, __reg("a2") STRPTR value)="\tjsr\t-102(a6)";
#define HttpTransactionAddHeader(txn, name, value) __HttpTransactionAddHeader(HttpBase, (txn), (name), (value))

void __HttpTransactionClearHeaders(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-108(a6)";
#define HttpTransactionClearHeaders(txn) __HttpTransactionClearHeaders(HttpBase, (txn))

LONG __HttpTransactionPerform(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-114(a6)";
#define HttpTransactionPerform(txn) __HttpTransactionPerform(HttpBase, (txn))

LONG __HttpTransactionPerformAsync(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-120(a6)";
#define HttpTransactionPerformAsync(txn) __HttpTransactionPerformAsync(HttpBase, (txn))

BOOL __HttpTransactionIsComplete(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-126(a6)";
#define HttpTransactionIsComplete(txn) __HttpTransactionIsComplete(HttpBase, (txn))

LONG __WaitHttpTransaction(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("d0") ULONG timeout_secs)="\tjsr\t-132(a6)";
#define WaitHttpTransaction(txn, timeout_secs) __WaitHttpTransaction(HttpBase, (txn), (timeout_secs))

void __AbortHttpTransaction(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-138(a6)";
#define AbortHttpTransaction(txn) __AbortHttpTransaction(HttpBase, (txn))

LONG __HttpTransactionGetStatusCode(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-144(a6)";
#define HttpTransactionGetStatusCode(txn) __HttpTransactionGetStatusCode(HttpBase, (txn))

STRPTR __HttpTransactionGetStatusLine(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-150(a6)";
#define HttpTransactionGetStatusLine(txn) __HttpTransactionGetStatusLine(HttpBase, (txn))

STRPTR __HttpTransactionRespHeader(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("a1") STRPTR header_name)="\tjsr\t-156(a6)";
#define HttpTransactionRespHeader(txn, header_name) __HttpTransactionRespHeader(HttpBase, (txn), (header_name))

struct List *__HttpTransactionRespHeaders(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-162(a6)";
#define HttpTransactionRespHeaders(txn) __HttpTransactionRespHeaders(HttpBase, (txn))

LONG __HttpTransactionReadBody(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("a1") APTR buffer, __reg("d0") ULONG buflen)="\tjsr\t-168(a6)";
#define HttpTransactionReadBody(txn, buffer, buflen) __HttpTransactionReadBody(HttpBase, (txn), (buffer), (buflen))

STRPTR __HttpTransactionGetRedirectLocation(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-174(a6)";
#define HttpTransactionGetRedirectLocation(txn) __HttpTransactionGetRedirectLocation(HttpBase, (txn))

LONG __HttpTransactionGetContentLength(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-180(a6)";
#define HttpTransactionGetContentLength(txn) __HttpTransactionGetContentLength(HttpBase, (txn))

ULONG __HttpTransactionGetBytesReceived(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-186(a6)";
#define HttpTransactionGetBytesReceived(txn) __HttpTransactionGetBytesReceived(HttpBase, (txn))

LONG __HttpTransactionGetTiming(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("a1") struct HttpTiming *timing)="\tjsr\t-192(a6)";
#define HttpTransactionGetTiming(txn, timing) __HttpTransactionGetTiming(HttpBase, (txn), (timing))

LONG __HttpTransactionGetLastError(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn)="\tjsr\t-198(a6)";
#define HttpTransactionGetLastError(txn) __HttpTransactionGetLastError(HttpBase, (txn))

LONG __SetHttpTransactionHook(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("d0") ULONG type, __reg("a1") struct Hook *hook)="\tjsr\t-204(a6)";
#define SetHttpTransactionHook(txn, type, hook) __SetHttpTransactionHook(HttpBase, (txn), (type), (hook))


/* Tier 3 - HttpConnection streaming / WebDAV / custom protocols. */

struct HttpConnection *__OpenHttpConnection(__reg("a6") void *, __reg("a0") struct HttpSession *session, __reg("a1") STRPTR host, __reg("d0") ULONG port, __reg("d1") LONG ssl)="\tjsr\t-210(a6)";
#define OpenHttpConnection(session, host, port, ssl) __OpenHttpConnection(HttpBase, (session), (host), (port), (ssl))

void __CloseHttpConnection(__reg("a6") void *, __reg("a0") struct HttpConnection *conn)="\tjsr\t-216(a6)";
#define CloseHttpConnection(conn) __CloseHttpConnection(HttpBase, (conn))

LONG __HttpConnectionWrite(__reg("a6") void *, __reg("a0") struct HttpConnection *conn, __reg("a1") APTR buffer, __reg("d0") ULONG len)="\tjsr\t-222(a6)";
#define HttpConnectionWrite(conn, buffer, len) __HttpConnectionWrite(HttpBase, (conn), (buffer), (len))

LONG __HttpConnectionRead(__reg("a6") void *, __reg("a0") struct HttpConnection *conn, __reg("a1") APTR buffer, __reg("d0") ULONG len)="\tjsr\t-228(a6)";
#define HttpConnectionRead(conn, buffer, len) __HttpConnectionRead(HttpBase, (conn), (buffer), (len))

LONG __HttpConnectionSendRequest(__reg("a6") void *, __reg("a0") struct HttpConnection *conn, __reg("a1") STRPTR method, __reg("a2") STRPTR path, __reg("a3") struct TagItem *tags)="\tjsr\t-234(a6)";
#define HttpConnectionSendRequest(conn, method, path, tags) __HttpConnectionSendRequest(HttpBase, (conn), (method), (path), (tags))

LONG __HttpConnectionReadResponseLine(__reg("a6") void *, __reg("a0") struct HttpConnection *conn, __reg("a1") STRPTR buffer, __reg("d0") ULONG buflen)="\tjsr\t-240(a6)";
#define HttpConnectionReadResponseLine(conn, buffer, buflen) __HttpConnectionReadResponseLine(HttpBase, (conn), (buffer), (buflen))

LONG __HttpConnectionReadResponseHeaders(__reg("a6") void *, __reg("a0") struct HttpConnection *conn)="\tjsr\t-246(a6)";
#define HttpConnectionReadResponseHeaders(conn) __HttpConnectionReadResponseHeaders(HttpBase, (conn))

LONG __HttpConnectionReadBodyChunk(__reg("a6") void *, __reg("a0") struct HttpConnection *conn, __reg("a1") APTR buffer, __reg("d0") ULONG buflen)="\tjsr\t-252(a6)";
#define HttpConnectionReadBodyChunk(conn, buffer, buflen) __HttpConnectionReadBodyChunk(HttpBase, (conn), (buffer), (buflen))

LONG __HttpConnectionWriteBodyChunk(__reg("a6") void *, __reg("a0") struct HttpConnection *conn, __reg("a1") APTR buffer, __reg("d0") ULONG len)="\tjsr\t-258(a6)";
#define HttpConnectionWriteBodyChunk(conn, buffer, len) __HttpConnectionWriteBodyChunk(HttpBase, (conn), (buffer), (len))

BOOL __HttpConnectionIsAlive(__reg("a6") void *, __reg("a0") struct HttpConnection *conn)="\tjsr\t-264(a6)";
#define HttpConnectionIsAlive(conn) __HttpConnectionIsAlive(HttpBase, (conn))

void __ResetHttpConnection(__reg("a6") void *, __reg("a0") struct HttpConnection *conn)="\tjsr\t-270(a6)";
#define ResetHttpConnection(conn) __ResetHttpConnection(HttpBase, (conn))

STRPTR __HttpConnectionRespHeader(__reg("a6") void *, __reg("a0") struct HttpConnection *conn, __reg("a1") STRPTR header_name)="\tjsr\t-276(a6)";
#define HttpConnectionRespHeader(conn, header_name) __HttpConnectionRespHeader(HttpBase, (conn), (header_name))

struct List *__HttpConnectionRespHeaders(__reg("a6") void *, __reg("a0") struct HttpConnection *conn)="\tjsr\t-282(a6)";
#define HttpConnectionRespHeaders(conn) __HttpConnectionRespHeaders(HttpBase, (conn))

LONG __HttpConnectionGetStatusCode(__reg("a6") void *, __reg("a0") struct HttpConnection *conn)="\tjsr\t-288(a6)";
#define HttpConnectionGetStatusCode(conn) __HttpConnectionGetStatusCode(HttpBase, (conn))

STRPTR __HttpConnectionGetStatusLine(__reg("a6") void *, __reg("a0") struct HttpConnection *conn)="\tjsr\t-294(a6)";
#define HttpConnectionGetStatusLine(conn) __HttpConnectionGetStatusLine(HttpBase, (conn))


/* URL parsing and encoding utilities. */

struct ParsedUrl *__ParseHttpUrl(__reg("a6") void *, __reg("a0") STRPTR url)="\tjsr\t-300(a6)";
#define ParseHttpUrl(url) __ParseHttpUrl(HttpBase, (url))

void __DisposeHttpUrl(__reg("a6") void *, __reg("a0") struct ParsedUrl *url)="\tjsr\t-306(a6)";
#define DisposeHttpUrl(url) __DisposeHttpUrl(HttpBase, (url))

STRPTR __BuildHttpUrl(__reg("a6") void *, __reg("a0") struct ParsedUrl *url)="\tjsr\t-312(a6)";
#define BuildHttpUrl(url) __BuildHttpUrl(HttpBase, (url))

STRPTR __HttpUrlEncode(__reg("a6") void *, __reg("a0") STRPTR str)="\tjsr\t-318(a6)";
#define HttpUrlEncode(str) __HttpUrlEncode(HttpBase, (str))

STRPTR __HttpUrlDecode(__reg("a6") void *, __reg("a0") STRPTR str)="\tjsr\t-324(a6)";
#define HttpUrlDecode(str) __HttpUrlDecode(HttpBase, (str))

STRPTR __HttpPathEncode(__reg("a6") void *, __reg("a0") STRPTR path)="\tjsr\t-330(a6)";
#define HttpPathEncode(path) __HttpPathEncode(HttpBase, (path))

STRPTR __HttpBuildQueryString(__reg("a6") void *, __reg("a0") struct List *pairs)="\tjsr\t-336(a6)";
#define HttpBuildQueryString(pairs) __HttpBuildQueryString(HttpBase, (pairs))


/* Optional HttpCookieJar (attach via HttpSessionAttachCookieJar). */

struct HttpCookieJar *__NewHttpCookieJarA(__reg("a6") void *, __reg("a0") struct TagItem *tags)="\tjsr\t-342(a6)";
#define NewHttpCookieJarA(tags) __NewHttpCookieJarA(HttpBase, (tags))

#if !defined(NO_INLINE_STDARG) && (__STDC__ == 1L) && (__STDC_VERSION__ >= 199901L)
struct HttpCookieJar *__NewHttpCookieJar(__reg("a6") void *, ...)="\tmove.l\ta0,-(a7)\n\tlea\t4(a7),a0\n\tjsr\t-342(a6)\n\tmovea.l\t(a7)+,a0";
#define NewHttpCookieJar(...) __NewHttpCookieJar(HttpBase, __VA_ARGS__)
#endif

void __DisposeHttpCookieJar(__reg("a6") void *, __reg("a0") struct HttpCookieJar *jar)="\tjsr\t-348(a6)";
#define DisposeHttpCookieJar(jar) __DisposeHttpCookieJar(HttpBase, (jar))

LONG __LoadHttpCookieJar(__reg("a6") void *, __reg("a0") struct HttpCookieJar *jar, __reg("a1") STRPTR filename)="\tjsr\t-354(a6)";
#define LoadHttpCookieJar(jar, filename) __LoadHttpCookieJar(HttpBase, (jar), (filename))

LONG __SaveHttpCookieJar(__reg("a6") void *, __reg("a0") struct HttpCookieJar *jar, __reg("a1") STRPTR filename)="\tjsr\t-360(a6)";
#define SaveHttpCookieJar(jar, filename) __SaveHttpCookieJar(HttpBase, (jar), (filename))

void __FlushHttpCookieJar(__reg("a6") void *, __reg("a0") struct HttpCookieJar *jar, __reg("d0") ULONG max_count)="\tjsr\t-366(a6)";
#define FlushHttpCookieJar(jar, max_count) __FlushHttpCookieJar(HttpBase, (jar), (max_count))

LONG __SetHttpCookie(__reg("a6") void *, __reg("a0") struct HttpCookieJar *jar, __reg("a1") STRPTR cookie_line)="\tjsr\t-372(a6)";
#define SetHttpCookie(jar, cookie_line) __SetHttpCookie(HttpBase, (jar), (cookie_line))

STRPTR __GetHttpCookieString(__reg("a6") void *, __reg("a0") struct HttpCookieJar *jar, __reg("a1") STRPTR url)="\tjsr\t-378(a6)";
#define GetHttpCookieString(jar, url) __GetHttpCookieString(HttpBase, (jar), (url))

LONG __SetHttpError(__reg("a6") void *, __reg("d0") LONG code)="\tjsr\t-384(a6)";
#define SetHttpError(code) __SetHttpError(HttpBase, (code))

LONG __HttpFault(__reg("a6") void *, __reg("d0") LONG code, __reg("a0") STRPTR header, __reg("a1") STRPTR buffer, __reg("d1") LONG len)="\tjsr\t-390(a6)";
#define HttpFault(code, header, buffer, len) __HttpFault(HttpBase, (code), (header), (buffer), (len))


/* URL part helpers (dos PathPart/FilePart style; caller frees with Free()). */

STRPTR __HttpUriSchemePart(__reg("a6") void *, __reg("a0") STRPTR url)="\tjsr\t-396(a6)";
#define HttpUriSchemePart(url) __HttpUriSchemePart(HttpBase, (url))

STRPTR __HttpUriHostPart(__reg("a6") void *, __reg("a0") STRPTR url)="\tjsr\t-402(a6)";
#define HttpUriHostPart(url) __HttpUriHostPart(HttpBase, (url))

STRPTR __HttpUriPathPart(__reg("a6") void *, __reg("a0") STRPTR url)="\tjsr\t-408(a6)";
#define HttpUriPathPart(url) __HttpUriPathPart(HttpBase, (url))

STRPTR __HttpUriFilePart(__reg("a6") void *, __reg("a0") STRPTR url)="\tjsr\t-414(a6)";
#define HttpUriFilePart(url) __HttpUriFilePart(HttpBase, (url))

STRPTR __HttpUriQueryPart(__reg("a6") void *, __reg("a0") STRPTR url)="\tjsr\t-420(a6)";
#define HttpUriQueryPart(url) __HttpUriQueryPart(HttpBase, (url))

STRPTR __HttpUriParentPart(__reg("a6") void *, __reg("a0") STRPTR url)="\tjsr\t-426(a6)";
#define HttpUriParentPart(url) __HttpUriParentPart(HttpBase, (url))

STRPTR __HttpUriAuthorityPart(__reg("a6") void *, __reg("a0") STRPTR url)="\tjsr\t-432(a6)";
#define HttpUriAuthorityPart(url) __HttpUriAuthorityPart(HttpBase, (url))

STRPTR __HttpJoinUri(__reg("a6") void *, __reg("a0") STRPTR base_url, __reg("a1") STRPTR relative_url)="\tjsr\t-438(a6)";
#define HttpJoinUri(base_url, relative_url) __HttpJoinUri(HttpBase, (base_url), (relative_url))


/* TLS peer certificate (after HTTPS HttpTransactionPerform). */

LONG __HttpTransactionGetPeerCert(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("a1") struct HttpSslPeerCert *cert)="\tjsr\t-444(a6)";
#define HttpTransactionGetPeerCert(txn, cert) __HttpTransactionGetPeerCert(HttpBase, (txn), (cert))

void __HttpPeerCertFree(__reg("a6") void *, __reg("a0") struct HttpSslPeerCert *cert)="\tjsr\t-450(a6)";
#define HttpPeerCertFree(cert) __HttpPeerCertFree(HttpBase, (cert))

STRPTR __HttpTransactionRespHeaderNext(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("a1") STRPTR header_name, __reg("a2") STRPTR prev_value)="\tjsr\t-456(a6)";
#define HttpTransactionRespHeaderNext(txn, header_name, prev_value) __HttpTransactionRespHeaderNext(HttpBase, (txn), (header_name), (prev_value))

BOOL __HttpTransactionRespHeaderByIndex(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("d0") ULONG index, __reg("a1") STRPTR *name_out, __reg("a2") STRPTR *value_out)="\tjsr\t-462(a6)";
#define HttpTransactionRespHeaderByIndex(txn, index, name_out, value_out) __HttpTransactionRespHeaderByIndex(HttpBase, (txn), (index), (name_out), (value_out))

LONG __HttpTransactionGetCipher(__reg("a6") void *, __reg("a0") struct HttpTransaction *txn, __reg("a1") STRPTR buf, __reg("d0") ULONG buflen)="\tjsr\t-468(a6)";
#define HttpTransactionGetCipher(txn, buf, buflen) __HttpTransactionGetCipher(HttpBase, (txn), (buf), (buflen))


#endif /* INLINE_AMIHTTP_PROTOS_H */
