#ifndef INLINE_AMIHTTP_H
#define INLINE_AMIHTTP_H

/*
** GCC format inline files.
**
**
** Generated by LibDescConverter from an sfd file
*/

/*"amihttp.library" */
/*--- functions in V1 or higher --- */

/* Tier 0 - Per-process configuration (after OpenLibrary only). */

/* Bootstrap: OpenLibrary(AMIHTTPNAME, AMIHTTPVERSION) is sufficient.  bsdsocket */
/* opens on first HTTP use; amisslmaster / OpenAmiSSLTags on first HTTPS use */

#define HttpBaseTagList(tags)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct TagItem *p0 __asm("a0") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-30:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpError()    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-36:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpGetErrorString(code)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register LONG p0 __asm("d0") = (code);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-42:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* Tier 1 - HttpSession persistent client context. */

#define NewHttpSession()    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-48:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeHttpSession(session)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpSession *p0 __asm("a0") = (session);   \
	__asm volatile ("jsr a6@(-54:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define SetHttpSessionAttrsA(session, tags)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpSession *p0 __asm("a0") = (session);   \
	register struct TagItem *p1 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-60:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpSessionAttachCookieJar(session, jar)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpSession *p0 __asm("a0") = (session);   \
	register struct HttpCookieJar *p1 __asm("a1") = (jar);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-66:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpSessionDetachCookieJar(session)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpSession *p0 __asm("a0") = (session);   \
	__asm volatile ("jsr a6@(-72:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define SetHttpSessionHook(session, type, hook)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpSession *p0 __asm("a0") = (session);   \
	register ULONG p1 __asm("d0") = (type);   \
	register struct Hook *p2 __asm("a1") = (hook);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-78:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* Tier 2 - HttpTransaction request/response (primary API). */

#define NewHttpTransaction(session)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpSession *p0 __asm("a0") = (session);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-84:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeHttpTransaction(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	__asm volatile ("jsr a6@(-90:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define SetHttpTransactionAttrsA(txn, tags)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register struct TagItem *p1 __asm("a1") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-96:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionAddHeader(txn, name, value)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register STRPTR p1 __asm("a1") = (name);   \
	register STRPTR p2 __asm("a2") = (value);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-102:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionClearHeaders(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	__asm volatile ("jsr a6@(-108:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define HttpTransactionPerform(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-114:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionPerformAsync(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-120:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionIsComplete(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-126:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define WaitHttpTransaction(txn, timeout_secs)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register ULONG p1 __asm("d0") = (timeout_secs);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-132:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define AbortHttpTransaction(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	__asm volatile ("jsr a6@(-138:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define HttpTransactionGetStatusCode(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-144:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionGetStatusLine(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-150:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionRespHeader(txn, header_name)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register STRPTR p1 __asm("a1") = (header_name);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-156:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionRespHeaders(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-162:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionReadBody(txn, buffer, buflen)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR p1 __asm("a1") = (buffer);   \
	register ULONG p2 __asm("d0") = (buflen);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-168:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionGetRedirectLocation(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-174:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionGetContentLength(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-180:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionGetBytesReceived(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-186:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionGetTiming(txn, timing)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register struct HttpTiming *p1 __asm("a1") = (timing);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-192:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionGetLastError(txn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-198:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define SetHttpTransactionHook(txn, type, hook)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register ULONG p1 __asm("d0") = (type);   \
	register struct Hook *p2 __asm("a1") = (hook);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-204:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* Tier 3 - HttpConnection streaming / WebDAV / custom protocols. */

#define OpenHttpConnection(session, host, port, ssl)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpSession *p0 __asm("a0") = (session);   \
	register STRPTR p1 __asm("a1") = (host);   \
	register ULONG p2 __asm("d0") = (port);   \
	register BOOL p3 __asm("d1") = (ssl);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-210:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define CloseHttpConnection(conn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	__asm volatile ("jsr a6@(-216:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define HttpConnectionWrite(conn, buffer, len)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register APTR p1 __asm("a1") = (buffer);   \
	register ULONG p2 __asm("d0") = (len);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-222:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionRead(conn, buffer, len)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register APTR p1 __asm("a1") = (buffer);   \
	register ULONG p2 __asm("d0") = (len);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-228:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionSendRequest(conn, method, path, tags)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (method);   \
	register STRPTR p2 __asm("a2") = (path);   \
	register struct TagItem *p3 __asm("a3") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-234:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionReadResponseLine(conn, buffer, buflen)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (buffer);   \
	register ULONG p2 __asm("d0") = (buflen);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-240:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionReadResponseHeaders(conn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-246:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionReadBodyChunk(conn, buffer, buflen)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register APTR p1 __asm("a1") = (buffer);   \
	register ULONG p2 __asm("d0") = (buflen);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-252:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionWriteBodyChunk(conn, buffer, len)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register APTR p1 __asm("a1") = (buffer);   \
	register ULONG p2 __asm("d0") = (len);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-258:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionIsAlive(conn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-264:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define ResetHttpConnection(conn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	__asm volatile ("jsr a6@(-270:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define HttpConnectionRespHeader(conn, header_name)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register STRPTR p1 __asm("a1") = (header_name);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-276:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionRespHeaders(conn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-282:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionGetStatusCode(conn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-288:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpConnectionGetStatusLine(conn)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpConnection *p0 __asm("a0") = (conn);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-294:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* URL parsing and encoding utilities. */

#define ParseHttpUrl(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-300:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeHttpUrl(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct ParsedUrl *p0 __asm("a0") = (url);   \
	__asm volatile ("jsr a6@(-306:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define BuildHttpUrl(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct ParsedUrl *p0 __asm("a0") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-312:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpUrlEncode(str)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (str);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-318:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpUrlDecode(str)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (str);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-324:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpPathEncode(path)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (path);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-330:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpBuildQueryString(pairs)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct List *p0 __asm("a0") = (pairs);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-336:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* Optional HttpCookieJar (attach via HttpSessionAttachCookieJar). */

#define NewHttpCookieJar()    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-342:W);" : "+r"(b), "=r"(r) :  : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define DisposeHttpCookieJar(jar)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpCookieJar *p0 __asm("a0") = (jar);   \
	__asm volatile ("jsr a6@(-348:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define LoadHttpCookieJar(jar, filename)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpCookieJar *p0 __asm("a0") = (jar);   \
	register STRPTR p1 __asm("a1") = (filename);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-354:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define SaveHttpCookieJar(jar, filename)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpCookieJar *p0 __asm("a0") = (jar);   \
	register STRPTR p1 __asm("a1") = (filename);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-360:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define FlushHttpCookieJar(jar, max_count)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpCookieJar *p0 __asm("a0") = (jar);   \
	register ULONG p1 __asm("d0") = (max_count);   \
	__asm volatile ("jsr a6@(-366:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define SetHttpCookie(jar, cookie_line)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpCookieJar *p0 __asm("a0") = (jar);   \
	register STRPTR p1 __asm("a1") = (cookie_line);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-372:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define GetHttpCookieString(jar, url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpCookieJar *p0 __asm("a0") = (jar);   \
	register STRPTR p1 __asm("a1") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-378:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define SetHttpError(code)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register LONG p0 __asm("d0") = (code);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-384:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpFault(code, header, buffer, len)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register LONG p0 __asm("d0") = (code);   \
	register STRPTR p1 __asm("a0") = (header);   \
	register STRPTR p2 __asm("a1") = (buffer);   \
	register LONG p3 __asm("d1") = (len);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-390:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* URL part helpers (dos PathPart/FilePart style; caller frees with Free()). */

#define HttpUriSchemePart(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-396:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpUriHostPart(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-402:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpUriPathPart(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-408:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpUriFilePart(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-414:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpUriQueryPart(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-420:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpUriParentPart(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-426:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpUriAuthorityPart(url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-432:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpJoinUri(base_url, relative_url)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register STRPTR p0 __asm("a0") = (base_url);   \
	register STRPTR p1 __asm("a1") = (relative_url);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-438:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


/* TLS peer certificate (after HTTPS HttpTransactionPerform). */

#define HttpTransactionGetPeerCert(txn, cert)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register struct HttpSslPeerCert *p1 __asm("a1") = (cert);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-444:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpPeerCertFree(cert)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpSslPeerCert *p0 __asm("a0") = (cert);   \
	__asm volatile ("jsr a6@(-450:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
})

#define HttpTransactionRespHeaderNext(txn, header_name, prev_value)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register STRPTR p1 __asm("a1") = (header_name);   \
	register STRPTR p2 __asm("a2") = (prev_value);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-456:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionRespHeaderByIndex(txn, index, name_out, value_out)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register ULONG p1 __asm("d0") = (index);   \
	register STRPTR *p2 __asm("a1") = (name_out);   \
	register STRPTR *p3 __asm("a2") = (value_out);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-462:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2), "r"(p3) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define NewHttpCookieJarTags(tags)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct TagItem *p0 __asm("a0") = (tags);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-468:W);" : "+r"(b), "=r"(r) : "r"(p0) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})

#define HttpTransactionGetCipher(txn, buf, buflen)    \
({  \
	register void *b __asm("a6") = HttpBase;  \
	register struct HttpTransaction *p0 __asm("a0") = (txn);   \
	register STRPTR p1 __asm("a1") = (buf);   \
	register ULONG p2 __asm("d0") = (buflen);   \
	register APTR r __asm("d0");   \
	__asm volatile ("jsr a6@(-474:W);" : "+r"(b), "=r"(r) : "r"(p0), "r"(p1), "r"(p2) : "d0", "d1", "a0", "a1", "fp0", "fp1", "cc", "memory");    \
	r;   \
})


#endif /* INLINE_AMIHTTP_H */
