/*
 * SPDX-License-Identifier: BSD-2-Clause
 * Copyright 2026 amigazen project
 *
 * amihttp.h - proto/pragma dispatcher for amihttp.library callers
 *
 * Generated by LibDescConverter from an sfd file; variadic tag wrappers
 * are maintained for SDK publication.
 */

#ifndef PROTO_AMIHTTP_H
#define PROTO_AMIHTTP_H

#include <clib/amihttp_protos.h>

#ifndef _NO_INLINE

#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_AMIHTTP_PRAGMAS_H
#include <pragmas/amihttp_pragmas.h>
#endif /* PRAGMAS_AMIHTTP_PRAGMAS_H */

#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_AMIHTTP_LIB_H
#include <pragma/amihttp_lib.h>
#endif /* PRAGMA_AMIHTTP_LIB_H */

#elif defined(__VBCC__)

#ifndef INLINE_AMIHTTP_PROTOS_H
#include <inline/amihttp_protos.h>
#endif /* INLINE_AMIHTTP_PROTOS_H */

#elif defined(__GNUC__)

#if defined(mc68000)
# ifdef __AROS__
#  include <defines/amihttp.h>
# else
#  ifndef INLINE_AMIHTTP_H
#   include <inline/amihttp.h>
#  endif /* INLINE_AMIHTTP_H */
# endif /* __AROS__ */
#endif /* mc68000 */

#endif /* compiler */

#endif /* _NO_INLINE */

#ifndef __NOLIBBASE__
  extern struct Library *
# ifdef __CONSTLIBBASEDECL__
   __CONSTLIBBASEDECL__
# endif /* __CONSTLIBBASEDECL__ */
  HttpBase;
#endif /* __NOLIBBASE__ */

/****************************************************************************/
/* Variadic tag wrappers (mirror SocketBaseTags / SetWindowAttrs pattern)   */
/****************************************************************************/

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif
#ifndef LIBRARIES_AMIHTTP_H
#include <libraries/amihttp.h>
#endif

#ifndef HT_VARARGS_DEFINED
#define HT_VARARGS_DEFINED 1

static LONG HttpBaseTags(Tag tag1, ...)
{
    return HttpBaseTagList((struct TagItem *)&tag1);
}

static LONG SetHttpSessionAttrs(struct HttpSession *session, Tag tag1, ...)
{
    return SetHttpSessionAttrsA(session, (struct TagItem *)&tag1);
}

static LONG SetHttpTransactionAttrs(struct HttpTransaction *txn, Tag tag1, ...)
{
    return SetHttpTransactionAttrsA(txn, (struct TagItem *)&tag1);
}

static struct HttpCookieJar *HttpCookieJarTags(Tag tag1, ...)
{
    return NewHttpCookieJarTags((struct TagItem *)&tag1);
}

#endif /* HT_VARARGS_DEFINED */

#endif /* PROTO_AMIHTTP_H */
