#ifndef PROTO_AMIHTTP_H
#define PROTO_AMIHTTP_H

/*
** 'C' prototype and compiler specific header file combo
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef _NO_INLINE

#include <clib/amihttp_protos.h>

#else

#ifndef __NOLIBBASE__


#ifndef EXEC_LIBRARIES_H
#include <exec/libraries.h>
#endif /* EXEC_LIBRARIES_H */

extern struct Library * HttpBase;
#endif /* __NOLIBBASE__ */


#if defined(LATTICE) || defined(__SASC) || defined(_DCC)

#ifndef PRAGMAS_AMIHTTP_PRAGMAS_H
#include <pragmas/amihttp_pragmas.h>
#endif /* PRAGMAS_AMIHTTP_PRAGMAS_H */


#elif defined(AZTEC_C) || defined(__MAXON__) || defined(__STORM__)

#ifndef PRAGMA_AMIHTTP_LIB_H
#include <pragma/amihttp_lib.h>
#endif /* PRAGMA_AMIHTTP_LIB_H */

#elif defined(__VBCC__)

#include <clib/amihttp_protos.h>

#ifndef INLINE_AMIHTTP_PROTOS_H
#include <inline/amihttp_protos.h>
#endif /* INLINE_AMIHTTP_PROTOS_H */


#elif defined(__GNUC__)

#if defined(mc68000)
#ifndef INLINE_AMIHTTP_H
#include <inline/amihttp.h>
#endif /* INLINE_AMIHTTP_H */
#else
#include <clib/amihttp_protos.h>
#endif /* mc68000 */


/* Any other compiler */
#else

#include <clib/amihttp_protos.h>


#endif /* __GNUC__ */


#endif /* _NO_INLINE */

#endif /* PROTO_AMIHTTP_H */
