#ifndef CLIB_AMIHTTP_PROTOS_H
#define CLIB_AMIHTTP_PROTOS_H

/*
** 'C' prototypes. For use with 32 bit integers only.
**
**
** Generated by LibDescConverter from an sfd file
*/

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef LIBRARIES_AMIHTTP_H
#include <libraries/amihttp.h>
#endif

/*"amihttp.library"*/
/*--- functions in V1 or higher ---*/

/* Tier 0 - Per-process configuration (after OpenLibrary only).*/

/* Bootstrap: OpenLibrary(AMIHTTPNAME, AMIHTTPVERSION) is sufficient.  bsdsocket*/
/* opens on first HTTP use; amisslmaster / OpenAmiSSLTags on first HTTPS use*/

LONG HttpBaseTagsA(struct TagItem *tags);
LONG HttpBaseTags(Tag firstTag, ...);
LONG HttpError(void);
STRPTR HttpGetErrorString(LONG code);

/* Tier 1 - HttpSession persistent client context.*/

struct HttpSession *NewHttpSession(void);
void DisposeHttpSession(struct HttpSession *session);
LONG SetHttpSessionAttrsA(struct HttpSession *session, struct TagItem *tags);
LONG SetHttpSessionAttrs(struct HttpSession *session, ...);
LONG HttpSessionAttachCookieJar(struct HttpSession *session, struct HttpCookieJar *jar);
void HttpSessionDetachCookieJar(struct HttpSession *session);
LONG SetHttpSessionHook(struct HttpSession *session, ULONG type, struct Hook *hook);

/* Tier 2 - HttpTransaction request/response (primary API).*/

struct HttpTransaction *NewHttpTransaction(struct HttpSession *session);
void DisposeHttpTransaction(struct HttpTransaction *txn);
LONG SetHttpTransactionAttrsA(struct HttpTransaction *txn, struct TagItem *tags);
LONG SetHttpTransactionAttrs(struct HttpTransaction *txn, ...);
LONG HttpTransactionAddHeader(struct HttpTransaction *txn, STRPTR name, STRPTR value);
void HttpTransactionClearHeaders(struct HttpTransaction *txn);
LONG HttpTransactionPerform(struct HttpTransaction *txn);
LONG HttpTransactionPerformAsync(struct HttpTransaction *txn);
BOOL HttpTransactionIsComplete(struct HttpTransaction *txn);
LONG WaitHttpTransaction(struct HttpTransaction *txn, ULONG timeout_secs);
void AbortHttpTransaction(struct HttpTransaction *txn);
LONG HttpTransactionGetStatusCode(struct HttpTransaction *txn);
STRPTR HttpTransactionGetStatusLine(struct HttpTransaction *txn);
STRPTR HttpTransactionRespHeader(struct HttpTransaction *txn, STRPTR header_name);
struct List *HttpTransactionRespHeaders(struct HttpTransaction *txn);
LONG HttpTransactionReadBody(struct HttpTransaction *txn, APTR buffer, ULONG buflen);
STRPTR HttpTransactionGetRedirectLocation(struct HttpTransaction *txn);
LONG HttpTransactionGetContentLength(struct HttpTransaction *txn);
ULONG HttpTransactionGetBytesReceived(struct HttpTransaction *txn);
LONG HttpTransactionGetTiming(struct HttpTransaction *txn, struct HttpTiming *timing);
LONG HttpTransactionGetLastError(struct HttpTransaction *txn);
LONG SetHttpTransactionHook(struct HttpTransaction *txn, ULONG type, struct Hook *hook);

/* Tier 3 - HttpConnection streaming / WebDAV / custom protocols.*/

struct HttpConnection *OpenHttpConnection(struct HttpSession *session, STRPTR host, ULONG port, LONG ssl);
void CloseHttpConnection(struct HttpConnection *conn);
LONG HttpConnectionWrite(struct HttpConnection *conn, APTR buffer, ULONG len);
LONG HttpConnectionRead(struct HttpConnection *conn, APTR buffer, ULONG len);
LONG HttpConnectionSendRequest(struct HttpConnection *conn, STRPTR method, STRPTR path, struct TagItem *tags);
LONG HttpConnectionReadResponseLine(struct HttpConnection *conn, STRPTR buffer, ULONG buflen);
LONG HttpConnectionReadResponseHeaders(struct HttpConnection *conn);
LONG HttpConnectionReadBodyChunk(struct HttpConnection *conn, APTR buffer, ULONG buflen);
LONG HttpConnectionWriteBodyChunk(struct HttpConnection *conn, APTR buffer, ULONG len);
BOOL HttpConnectionIsAlive(struct HttpConnection *conn);
void ResetHttpConnection(struct HttpConnection *conn);
STRPTR HttpConnectionRespHeader(struct HttpConnection *conn, STRPTR header_name);
struct List *HttpConnectionRespHeaders(struct HttpConnection *conn);
LONG HttpConnectionGetStatusCode(struct HttpConnection *conn);
STRPTR HttpConnectionGetStatusLine(struct HttpConnection *conn);

/* URL parsing and encoding utilities.*/

struct ParsedUrl *ParseHttpUrl(STRPTR url);
void DisposeHttpUrl(struct ParsedUrl *url);
STRPTR BuildHttpUrl(struct ParsedUrl *url);
STRPTR HttpUrlEncode(STRPTR str);
STRPTR HttpUrlDecode(STRPTR str);
STRPTR HttpPathEncode(STRPTR path);
STRPTR HttpBuildQueryString(struct List *pairs);

/* Optional HttpCookieJar (attach via HttpSessionAttachCookieJar).*/

struct HttpCookieJar *NewHttpCookieJarA(struct TagItem *tags);
struct HttpCookieJar *NewHttpCookieJar(Tag firstTag, ...);
void DisposeHttpCookieJar(struct HttpCookieJar *jar);
LONG LoadHttpCookieJar(struct HttpCookieJar *jar, STRPTR filename);
LONG SaveHttpCookieJar(struct HttpCookieJar *jar, STRPTR filename);
void FlushHttpCookieJar(struct HttpCookieJar *jar, ULONG max_count);
LONG SetHttpCookie(struct HttpCookieJar *jar, STRPTR cookie_line);
STRPTR GetHttpCookieString(struct HttpCookieJar *jar, STRPTR url);
LONG SetHttpError(LONG code);
LONG HttpFault(LONG code, STRPTR header, STRPTR buffer, LONG len);

/* URL part helpers (dos PathPart/FilePart style; caller frees with Free()).*/

STRPTR HttpUriSchemePart(STRPTR url);
STRPTR HttpUriHostPart(STRPTR url);
STRPTR HttpUriPathPart(STRPTR url);
STRPTR HttpUriFilePart(STRPTR url);
STRPTR HttpUriQueryPart(STRPTR url);
STRPTR HttpUriParentPart(STRPTR url);
STRPTR HttpUriAuthorityPart(STRPTR url);
STRPTR HttpJoinUri(STRPTR base_url, STRPTR relative_url);

/* TLS peer certificate (after HTTPS HttpTransactionPerform).*/

LONG HttpTransactionGetPeerCert(struct HttpTransaction *txn, struct HttpSslPeerCert *cert);
void HttpPeerCertFree(struct HttpSslPeerCert *cert);
STRPTR HttpTransactionRespHeaderNext(struct HttpTransaction *txn, STRPTR header_name, STRPTR prev_value);
BOOL HttpTransactionRespHeaderByIndex(struct HttpTransaction *txn, ULONG index, STRPTR *name_out, STRPTR *value_out);
LONG HttpTransactionGetCipher(struct HttpTransaction *txn, STRPTR buf, ULONG buflen);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CLIB_AMIHTTP_PROTOS_H */
